name: make

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build libs
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install build-essential
        sudo apt install cmake
        sudo apt install libboost-all-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make
