name: make

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install z3
      run: |
        wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.12.1.tar.gz
        tar -xzf z3-4.12.1.tar.gz
        ls -l
        cd z3-z3-4.12.1
        python scripts/mk_make.py
        cd build
        make
        sudo make install
    - name: Install build libs
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install build-essential
        sudo apt install cmake
        sudo apt install libboost-all-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make
